### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chadbrewbaker** [chadbrewbaker/st#1]
- [ ]  Make failing arguments non-required
- [ ] Read both stdin and from file, readline then fixed length buffer
- [ ]  support both float and unsigned int
- [ ] get sum() working
- [ ] benchmark against wc and sort
